config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  # error pages
  %w( 404 422 500 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  root 'homepage#index'

  get 'loaderio-e85c09dfa65bcd2736be73c21b6715c4', to: 'loader#index'

  resources :articles, path: 'news'
  resources :artists, path: 'roster' do
    member do
      get :shop, to: 'artist_shops#show'
      get :download
    end
  end
  resources :awards
  resources :presses, path: 'press' do
    member do
      get :pdfdown
    end
  end

  get 'checkout/:id', to: 'purchases#checkout', as: 'checkout'
  post 'purchase_complete', to: 'purchases#create', as: 'purchase_complete'

  resources :purchases, only: [:show]
  resources :shops, path: 'shop'
  resources :releases 
  resources :videos 
  resources :abouts, path: 'about'
  resources :contact, only: [:index] do
    collection do
      post :deliver
    end
  end
  resources :composers
  resources :songwriters
  resources :producers
  resources :roster, path: 'artists'
  resources :catalogue
  resources :tweets
  resources :privacy
  resources :b_di_productions, path: 'bdiproductions'

  require 'sidekiq/web'
  require 'sidetiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/search', to: 'search#index'

  namespace :admin do
    resource :home
    resources :articles
    resources :tracks do
      collection do
        get :unassigned
      end
    end
    resources :production_companies
    resources :b_di_productions
    resources :shop_items 
    resources :artist_shops
    resources :artists
    resources :awards
    resources :audios 
    resources :audio_artists
    resources :presses
    resources :releases
    resources :videos 
    resources :abouts
    resources :users
    resources :genres
    resources :formats
    resources :staffs
    resources :types
    resources :productions
    resources :styles
    resources :instrumentations
    resources :moods
    resources :cats
    resources :placements
  end
  get 'admin' => 'admin/homes#show'
end

app/models/placement.rb
class Placement < ActiveRecord::Base
  has_many :artist_placements, dependent: :destroy
  has_many :artists, through: :artist_placements

  mount_uploader :image, PlacementUploader 
  crop_uploaded :image

  def preview
    title[0..30] + '..'
  end

  def embed(_youtube)
    youtube_id = url.split('=').last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end

  def vimeoid
    vimeo = url.split('.com/').last
  end
 
end

app/controllers/admin/placements_controller.rb
class Admin::PlacementsController < Admin::BaseController
  before_action :require_admin

  def index
    @placements = Placement.all.paginate(page: params[:page], per_page: 20).order('created_at DESC')
  end

  def show
    @placement = Placement.find(params[:id])
  end

  def new
    @placement = Placement.new
  end

  def edit
    @placement = Placement.find(params[:id])
  end

  def create
    @placement = Placement.new(placement_params)
    if @placement.save
      redirect_to admin_placements_path(@placement)
    else
      render :new
    end
  end

  def update
    @placement = Placement.find(params[:id])
    @placement.update(placement_params)

    redirect_to admin_placements_path(@placement)
  end

  def destroy
    @placement = Placement.find(params[:id])
    @placement.destroy

    redirect_to admin_placements_path
  end

  def placement_params
    params.require(:placement).permit(:title, :url, :created_at, :image, :image_crop_x,
                                  :image_crop_y, :image_crop_w, :image_crop_h, artist_ids: [])
  end
end

app/views/admin/placements/_form.html.erb
<%= simple_form_for([:admin, @placement], html: {multipart: true}) do |f| %>
  <%= f.input :title %><br />
  <%= f.input :url %><br /> 
  <%= f.association :artists, collection: Artist.order('name ASC') %><br />
  <%= f.input :created_at, as: :date, html5: true, class: 'btn btn-primary noborder', label: 'Created at' %> <br /><br />
  <%= f.file_field :image %> <br />
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<br /><br />

app/views/admin/placements/crop.html.erb
<div class="containernohome">
<div class="col-md-12 cropit">
<h4>Crop Your Image </h4>
<%= form_for [:admin, @placement] do |f| %>
  <%= f.cropbox :image %>
  <%= f.previewbox :image %>
  <%= f.submit 'Crop' %>
<% end %>
</div>
</div>
<div class="clear"></div>
<% content_for :extra_footer do %>
  <%= javascript_include_tag 'placements' %>
<% end %>

app/views/admin/placements/edit.html.erb
<%= render 'shared/adminnav' %>
<div class="col-md-9">
<h4> Edit A Placement </h4> 
 
 

<%= render partial: 'form' %></div></div>
<%= render 'shared/adminnavfooter' %>

app/views/admin/placements/index.html.erb
<%= render 'shared/adminnav' %>
<div class="col-md-9">
<h4> List Of Placements</h4><%= link_to "+ New", new_admin_placement_path, class: "btn btn-primary"  %>
<br /><br />


<table class="admin-table-news">
  <tbody> 
 <th class="a-one"><p>ID</p></th>
  <th class="a-one"><p>Image</p></th>
  <th class="a-two"><p>Title</p></th> 
  <th class="a-three"><p>Created At</p></th>  
  </tbody>
<% @placements.each do |placement| %>
  <tr> 
  <td class="a-one"><p><%= placement.id %></p></td>
  <td class="a-one"> 


    </td>
 
  <td class="a-two" style="padding-right:10px;"><p><%= link_to placement.title, edit_admin_placement_path(placement) %></p></td> 
  
  <td class="a-threes"><p><%= placement.created_at.strftime('%d/%m/%Y at %H:%m%p') %></p>
   
  </td> 
  <td class="a-four"> <%= link_to "Edit", edit_admin_placement_path(placement), :class =>  "btn btn-primary", :method => :get  %> 
   <%= link_to 'Delete', admin_placement_path(placement), method: :delete, class: "btn btn-primary"  %></td>

  </tr>

<% end %>
</table>
<br /><br />
 
</div>
</div> 
 
<%= render 'shared/adminnavfooter' %>

app/views/admin/placements/new.html.erb
<%= render 'shared/adminnav' %>
<div class="col-md-9">
<h4> Add A New Placement </h4> 
 
 

<%= render partial: 'form' %></div></div>
<%= render 'shared/adminnavfooter' %>