config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  # error pages
  %w( 404 422 500 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  root 'homepage#index'

  get 'loaderio-e85c09dfa65bcd2736be73c21b6715c4', to: 'loader#index'

  resources :articles, path: 'news'
  resources :artists, path: 'roster' do
    member do
      get :shop, to: 'artist_shops#show'
      get :download
    end
  end
  resources :awards
  resources :presses, path: 'press' do
    member do
      get :pdfdown
    end
  end

  get 'checkout/:id', to: 'purchases#checkout', as: 'checkout'
  post 'purchase_complete', to: 'purchases#create', as: 'purchase_complete'

  resources :purchases, only: [:show]
  resources :shops, path: 'shop'
  resources :releases 
  resources :videos 
  resources :abouts, path: 'about'
  resources :contact, only: [:index] do
    collection do
      post :deliver
    end
  end
  resources :composers
  resources :songwriters
  resources :producers
  resources :roster, path: 'artists'
  resources :catalogue
  resources :tweets
  resources :privacy
  resources :b_di_productions, path: 'bdiproductions'

  require 'sidekiq/web'
  require 'sidetiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/search', to: 'search#index'

  namespace :admin do
    resource :home
    resources :articles
    resources :tracks do
      collection do
        get :unassigned
      end
    end
    resources :production_companies
    resources :b_di_productions
    resources :shop_items 
    resources :artist_shops
    resources :artists
    resources :awards
    resources :audios 
    resources :audio_artists
    resources :presses
    resources :releases
    resources :videos 
    resources :abouts
    resources :users
    resources :genres
    resources :formats
    resources :staffs
    resources :types
    resources :productions
    resources :styles
    resources :instrumentations
    resources :moods
    resources :cats
    resources :placements
  end
  get 'admin' => 'admin/homes#show'
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :video_artists, dependent: :destroy
  has_many :artists, through: :video_artists

  mount_uploader :image, VideoUploader
  crop_uploaded :image

  def preview
    title[0..30] + '..'
  end

  def embed(_youtube)
    youtube_id = url.split('=').last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end

  def vimeoid
    vimeo = url.split('.com/').last
  end

  class << self
    def search(query, artist)
      query = (query && !query.empty?) ? "%#{query.downcase}%" : nil
      releases = Release.includes(:artists)
      releases = releases.where(artists: { id: artist }) if artist.present?
      releases = releases.where('lower(title) ILIKE ? or lower(body) ILIKE ?', query) if query
      releases
    end
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  before_action :require_admin

  def index
    @videos = Video.unscoped.all.paginate(page: params[:page], per_page: 20).order('videos.created_at DESC')
  end

  def show
    @video = Video.find(params[:id])
  end

  def new
    @video = Video.new
  end

  def edit
    @video = Video.find(params[:id])
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      if params[:video][:image].present?
        render :crop ## Render the view for cropping
      else
        redirect_to admin_videos_path(@video), notice: 'video was successfully created.'
      end
    else
      render :new
    end
  end

  def update
    @video = Video.find(params[:id])
    @video.update(video_params)
    if params[:video][:image].present?
      render :crop ## Render the view for cropping
    else
      redirect_to admin_videos_path(@video)
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    redirect_to admin_videos_path
  end

  def video_params
    params.require(:video).permit(:title, :url, :youtube, :vimeo, :created_at, :image, :image_crop_x,
                                  :image_crop_y, :image_crop_w, :image_crop_h, artist_ids: [])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @q = Video.ransack(params[:q])
    @videos = @q.result(distinct: true).paginate(page: params[:page], per_page: 24).order('videos.created_at DESC')
 end

  def show
    @video = Video.find(params[:id])
  end
end

app/views/videos/index.html.erb
<% content_for :title, "| Videos" %>
<div class="main-page-header">
  <div class="m-p-h">
    <%= link_to 'Home', root_path %>  
    <span class="break">></span> 
    <%= link_to 'Videos', videos_path %> 
    <br /><br />
    <span class="artist-name-main">
    Videos
    </span>
    <br /><br />
  </div>
</div> 
<br /><br />
<div class="containernohome">  
<div class="col-md-12"> 
    
      <%= search_form_for @q, url: url_for(videos_path) do |f| %>
     <div class="artists">
     <ul class="grid-items"> 
      <li class="col-md-3 col-xs-6 col-sm-3">
        <%= f.search_field :title_cont, class: 'form-control custom', placeholder: 'Search...' %>
      </li>

      <li class="col-md-3 col-xs-6 col-sm-3">
        <%= f.collection_select :artists_id_eq, Artist.inuse.order('name asc'), :id, :name, {include_blank: 'Songwriter'}, class: 'form-control custom' %>
      </li>

      <li class="col-md-6 col-xs-12 col-sm-6">
      <%= f.submit 'Search', class: 'btn btn-primary release-searching' %>
      </li>
 
</ul></div><br /><br /><br /><br />
      <% end %>
    </div>

<div class="col-md-12 nopadleft nopadright">
<% if @videos.empty? %>
    <h1><center><br /><br />We currently have no videos matching your search criteria<br /><br />Please try again<br /><br /><br /><br /></center></h1>
    <% else %>
    <% @videos.each do |video| %>
    <%= link_to(video_path(video)) do %>
      <div class="col-md-3 col-sm-3 videobox nopadleft" style="padding-bottom:20px;"> 
      <%= image_tag video.image.artistmain.url, :style => 'width:100%; height:100%;', :class => 'img-responsive artistmi' %> 
      <span></span> <p><%= video.preview %></p> 
       </div>
<% end %>
      <% end %> <% end %>
</div>
<div class="clear"></div>

    <div class="col-md-11"> 
    <div class="middle">
      <%= will_paginate @videos, :page_links => true, :previous_label => '<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>', :next_label => '<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>' %> <br /><br />
      </div>
    </div>
</div>
</div>
<div class="clear"></div>
  




 

app/views/videos/show.html.erb
<% content_for :title, "| Videos" %>
<div class="main-page-header">
<div class="m-p-h">
<%= link_to 'Home', root_path %>  <span class="break">></span>  <%= link_to 'Videos', videos_path %>  <span class="break">></span> <%= @video.title %>
<br /><br /> 
<span class="artist-name-main">
<%= @video.title %></span> 

<br />  <br />

 </div>
</div> 
<br />  <br />

 <div class="clear"></div>

 <div class='containernohome'> 
 
<% if @video.youtube == true %>
<div class="news" style="width:100%">
      <div class="col-md-12 col-sm-12"> 
      <div class="embed-container"><%= embed(@video.url) %>  </div>
      </div>

<% elsif @video.vimeo == true %>
<div class="news" style="width:100%">
<div class="videoWrapper">
<iframe src="https://player.vimeo.com/video/<%= @video.vimeoid %>" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> 
</div> 
<% end %>


<div class="clear"></div>
<h4>Related Artists:</h4></div>

 <% @video.artists.each do |artist| %>
 <div class="col-md-2 col-sm-4 col-xs-6" style="padding-left:0px;">
 
 <%= link_to (image_tag artist.photo.artistmain.url, :style => 'width:100%; height:100%;', :class => 'img-responsive artistmi'), artist_path(artist) %>

    <p class=""><%= link_to artist.name, artist_path(artist), :class =>'artist-name' %></p>
 </p>
  </div> 

<% end %>



    </div> </div>




    <div class="clear"></div>
  

  