config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  # error pages
  %w( 404 422 500 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  root 'homepage#index'

  get 'loaderio-e85c09dfa65bcd2736be73c21b6715c4', to: 'loader#index'

  resources :articles, path: 'news'
  resources :artists, path: 'roster' do
    member do
      get :shop, to: 'artist_shops#show'
      get :download
    end
  end
  resources :awards
  resources :presses, path: 'press' do
    member do
      get :pdfdown
    end
  end

  get 'checkout/:id', to: 'purchases#checkout', as: 'checkout'
  post 'purchase_complete', to: 'purchases#create', as: 'purchase_complete'

  resources :purchases, only: [:show]
  resources :shops, path: 'shop'
  resources :releases 
  resources :videos 
  resources :abouts, path: 'about'
  resources :contact, only: [:index] do
    collection do
      post :deliver
    end
  end
  resources :composers
  resources :songwriters
  resources :producers
  resources :roster, path: 'artists'
  resources :catalogue
  resources :tweets
  resources :privacy
  resources :b_di_productions, path: 'bdiproductions'

  require 'sidekiq/web'
  require 'sidetiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/search', to: 'search#index'

  namespace :admin do
    resource :home
    resources :articles
    resources :tracks do
      collection do
        get :unassigned
      end
    end
    resources :production_companies
    resources :b_di_productions
    resources :shop_items 
    resources :artist_shops
    resources :artists
    resources :awards
    resources :audios 
    resources :audio_artists
    resources :presses
    resources :releases
    resources :videos 
    resources :abouts
    resources :users
    resources :genres
    resources :formats
    resources :staffs
    resources :types
    resources :productions
    resources :styles
    resources :instrumentations
    resources :moods
    resources :cats
    resources :placements
  end
  get 'admin' => 'admin/homes#show'
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  def index
    @artists = Artist.all
    @producer_artists = @artists.where(producer: true).order('artists.name ASC')
  end
end

app/views/producers/index.html.erb
<% content_for :title, "| Producers" %>
<div class="main-page-header">
<div class="m-p-h">
<%= link_to 'Home', root_path %>  <span class="break">></span>  <%= link_to 'Producers', producers_path %> 
</span>
<br /><br />
<span class="artist-name-main">
Producers
</span>

 <br /><br /></div>
</div> 
  <br />  <br /> 

 <div class='containernohome'> 
 



 <div class="list-news  m-0" >
  



 
 
 
<ul class="grid-items"> 

  <% if defined?(@producer_artists) %>
  <% @producer_artists.each do |artist| %>
 
<li class="col-md-3 col-xs-6 col-sm-3 overflow-hidden overflow-hidden content">
 
<%= link_to(artist_path(artist)) do %>
<div class="content-overlay hidemob"></div>
 <%= image_tag artist.photo.artistmain.url, :class => 'img-responsive w-full object-cover content-image' %> 
  <div class="content-details fadeIn-top viewwidthrost hidemob">
            <h4 class=''>
              <%= artist.name %></h4> 
          </div>
          <h5 style="font-size:120%" class="dispmob"><%= artist.name %></h5>
 
  <% end %> <br />
</li>  
 <% end %> <% end %> 
</ul> 
 </div> 


</div>

<div class="clear"></div>
<br /><br >
 

<style> 

.viewwidthrost { 
  font-size: 120%;
}
.p-0 { padding: 0px; margin:10px;}
.overflow-hidden {
  overflow: hidden;
} 
.w-full {
  width: 100%;
}

.object-cover {
  object-fit: cover;
}

.content {
  position: relative;  
  overflow: hidden;
  float: left;
}

.content .content-overlay {
  background: rgba(132,143,129,0.9);
  position: absolute; 
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  opacity: 0;
  margin-right: 15px;
  margin-bottom: 21px;
  -webkit-transition: all 0.4s ease-in-out 0s;
  -moz-transition: all 0.4s ease-in-out 0s;
  transition: all 0.4s ease-in-out 0s;
}

.content:hover .content-overlay{
  opacity: 1;
}
   
 
.content-details {
  position: absolute;
  text-align: center;
  padding-left: 1em;
  padding-right: 1em;
  width: 100%;
  top: 50%;
  left: 50%;
  opacity: 0;
  -webkit-transform: translate(-50%, -50%);
  -moz-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  -webkit-transition: all 0.3s ease-in-out 0s;
  -moz-transition: all 0.3s ease-in-out 0s;
  transition: all 0.3s ease-in-out 0s;
}

.content:hover .content-details{
  top: 50%;
  left: 50%;
  opacity: 1;
}

.content-details h4{
  color: white !important;
  font-weight: 500;
  letter-spacing: 0.15em; 
  text-transform: uppercase;
  padding-top:0px !important;
}

.content-details p{
  color: #fff;
  font-size: 0.8em;
}

.fadeIn-bottom{
  top: 80%;
}

.fadeIn-top{
  top: 20%;
}

.fadeIn-left{
  left: 20%;
}

.fadeIn-right{
  left: 80%;
}

</style>