config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  # error pages
  %w( 404 422 500 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  root 'homepage#index'

  get 'loaderio-e85c09dfa65bcd2736be73c21b6715c4', to: 'loader#index'

  resources :articles, path: 'news'
  resources :artists, path: 'roster' do
    member do
      get :shop, to: 'artist_shops#show'
      get :download
    end
  end
  resources :awards
  resources :presses, path: 'press' do
    member do
      get :pdfdown
    end
  end

  get 'checkout/:id', to: 'purchases#checkout', as: 'checkout'
  post 'purchase_complete', to: 'purchases#create', as: 'purchase_complete'

  resources :purchases, only: [:show]
  resources :shops, path: 'shop'
  resources :releases 
  resources :videos 
  resources :abouts, path: 'about'
  resources :contact, only: [:index] do
    collection do
      post :deliver
    end
  end
  resources :composers
  resources :songwriters
  resources :producers
  resources :roster, path: 'artists'
  resources :catalogue
  resources :tweets
  resources :privacy
  resources :b_di_productions, path: 'bdiproductions'

  require 'sidekiq/web'
  require 'sidetiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/search', to: 'search#index'

  namespace :admin do
    resource :home
    resources :articles
    resources :tracks do
      collection do
        get :unassigned
      end
    end
    resources :production_companies
    resources :b_di_productions
    resources :shop_items 
    resources :artist_shops
    resources :artists
    resources :awards
    resources :audios 
    resources :audio_artists
    resources :presses
    resources :releases
    resources :videos 
    resources :abouts
    resources :users
    resources :genres
    resources :formats
    resources :staffs
    resources :types
    resources :productions
    resources :styles
    resources :instrumentations
    resources :moods
    resources :cats
    resources :placements
  end
  get 'admin' => 'admin/homes#show'
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :video_artists, dependent: :destroy
  has_many :artists, through: :video_artists

  mount_uploader :image, VideoUploader
  crop_uploaded :image

  def preview
    title[0..30] + '..'
  end

  def embed(_youtube)
    youtube_id = url.split('=').last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end

  def vimeoid
    vimeo = url.split('.com/').last
  end

  class << self
    def search(query, artist)
      query = (query && !query.empty?) ? "%#{query.downcase}%" : nil
      releases = Release.includes(:artists)
      releases = releases.where(artists: { id: artist }) if artist.present?
      releases = releases.where('lower(title) ILIKE ? or lower(body) ILIKE ?', query) if query
      releases
    end
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  before_action :require_admin

  def index
    @videos = Video.unscoped.all.paginate(page: params[:page], per_page: 20).order('videos.created_at DESC')
  end

  def show
    @video = Video.find(params[:id])
  end

  def new
    @video = Video.new
  end

  def edit
    @video = Video.find(params[:id])
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      if params[:video][:image].present?
        render :crop ## Render the view for cropping
      else
        redirect_to admin_videos_path(@video), notice: 'video was successfully created.'
      end
    else
      render :new
    end
  end

  def update
    @video = Video.find(params[:id])
    @video.update(video_params)
    if params[:video][:image].present?
      render :crop ## Render the view for cropping
    else
      redirect_to admin_videos_path(@video)
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    redirect_to admin_videos_path
  end

  def video_params
    params.require(:video).permit(:title, :url, :youtube, :vimeo, :created_at, :image, :image_crop_x,
                                  :image_crop_y, :image_crop_w, :image_crop_h, artist_ids: [])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @q = Video.ransack(params[:q])
    @videos = @q.result(distinct: true).paginate(page: params[:page], per_page: 24).order('videos.created_at DESC')
 end

  def show
    @video = Video.find(params[:id])
  end
end

app/views/admin/videos/_form.html.erb
<%= simple_form_for([:admin, @video], html: {multipart: true}) do |f| %>
  <%= f.input :title %><br />
  <%= f.input :url %><br />
  <%= f.input :youtube, label: 'YouTube ' %><br />
  <%= f.input :vimeo, label: 'Vimeo ' %><br />
  <%= f.association :artists, collection: Artist.order('name ASC') %><br />
  <%= f.input :created_at, as: :date, html5: true, class: 'btn btn-primary noborder', label: 'Created at' %> <br /><br />
  <%= f.file_field :image %> <br />
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<br /><br />

app/views/admin/videos/crop.html.erb
<div class="containernohome">
<div class="col-md-12 cropit">
<h4>Crop Your Image </h4>
<%= form_for [:admin, @video] do |f| %>
  <%= f.cropbox :image %>
  <%= f.previewbox :image %>
  <%= f.submit 'Crop' %>
<% end %>
</div>
</div>
<div class="clear"></div>
<% content_for :extra_footer do %>
  <%= javascript_include_tag 'videos' %>
<% end %>

app/views/admin/videos/edit.html.erb
<%= render 'shared/adminnav' %>
<div class="col-md-9">
<h4> Edit A YouTube Video </h4> 
 
 

<%= render partial: 'form' %></div></div>
<%= render 'shared/adminnavfooter' %>

app/views/admin/videos/index.html.erb
<%= render 'shared/adminnav' %>
<div class="col-md-9">
<h4> List Of Videos</h4><%= link_to "+ New", new_admin_video_path, class: "btn btn-primary"  %>
<br /><br />


<table class="admin-table-news">
  <tbody> 
 <th class="a-one"><p>ID</p></th>
  <th class="a-one"><p>Image</p></th>
  <th class="a-two"><p>Title</p></th> 
  <th class="a-three"><p>Created At</p></th>  
  </tbody>
<% @videos.each do |video| %>
  <tr> 
  <td class="a-one"><p><%= video.id %></p></td>
  <td class="a-one"> 


    <% if video.image.blank? %>
  <% else %>
  <%= image_tag video.image.thumbnail.url, :class =>  "imagethumb admin-artist"  %>
  <% end %></td>
 
  <td class="a-two" style="padding-right:10px;"><p><%= link_to video.title, video_path(video) %></p></td> 
  
  <td class="a-threes"><p><%= video.created_at.strftime('%d/%m/%Y at %H:%m%p') %></p>
   
  </td> 
  <td class="a-four"> <%= link_to "Edit", edit_admin_video_path(video), :class =>  "btn btn-primary", :method => :get  %> 
   <%= link_to 'Delete', admin_video_path(video), method: :delete, class: "btn btn-primary"  %></td>

  </tr>

<% end %>
</table>
<br /><br />
<div class="col-md-10"> 
    <div class="middle">
      <%= will_paginate @artists, :page_links => true, :previous_label => '<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>', :next_label => '<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>' %>
      </div>
    </div>
</div>
</div> 
 
<%= render 'shared/adminnavfooter' %>

app/views/admin/videos/new.html.erb
<%= render 'shared/adminnav' %>
<div class="col-md-9">
<h4> Add A New Video </h4> 
 
 

<%= render partial: 'form' %></div></div>
<%= render 'shared/adminnavfooter' %>

app/views/admin/videos/show.html.erb
<h1><%= @video.title %></h1> 
  <%= image_tag @video.photo.url %><br />
    <%= @video.url %><br /><br />
<p><b>Artist:</b> <%= @video.artists.pluck(:name).map{|n| n.split(' ').map!(&:capitalize).join(' ')}.join(', ') %></p>

<%= link_to "Back To video", admin_videos_path, :class =>  "btn-primary", :method => :get  %> 
<%= link_to "Edit", edit_admin_video_path, :class =>  "btn-primary", :method => :get  %> 


</div><%= render 'shared/adminnavfooter' %>